### PR TITLE
index: add vanity import for gonum.org/v1/tools

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Review by kortschak — APPROVED** [review]

**Comment by sbinet** [comment]
I suppose I could merge this in (as in, I have the karma) but I am not sure whether there isn't something to do on the actual web site to pick that up.
TL;DR: I'd prefer if @btracey was the one to hold the chainsaw :)

**Comment by btracey** [comment]
I don't think there's anything on the website. This is between the Go command and HTML.

Not exactly sure what you mean by "I should hold the chainsaw"

**Review by btracey — APPROVED** [review]

**Comment by sbinet** [comment]
It was just a lousy not-funny joke (which sounded better in my brain.)
Sorry :)

**Comment by sbinet** [comment]
hum...

this still fails:
```
$>  go get -u -v gonum.org/v1/tools/...
Fetching https://gonum.org/v1/tools?go-get=1
Parsing meta tags from https://gonum.org/v1/tools?go-get=1 (status code 404)
package gonum.org/v1/tools/...: unrecognized import path "gonum.org/v1/tools/..." (parse https://gonum.org/v1/tools?go-get=1: no go-import meta tags (meta tag gonum.org/v1/gonum did not match import path gonum.org/v1/tools, meta tag gonum.org/v1/plot did not match import path gonum.org/v1/tools, meta tag gonum.org/v1/netlib did not match import path gonum.org/v1/tools, meta tag gonum.org/v1/hdf5 did not match import path gonum.org/v1/tools))

$> curl -L https://gonum.org/v1/tools?go-get=1
<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  
  <meta name="go-import" content="gonum.org/v1/gonum git https://github.com/gonum/gonum">
  <meta name="go-import" content="gonum.org/v1/plot git https://github.com/gonum/plot">
  <meta name="go-import" content="gonum.org/v1/netlib git https://github.com/gonum/netlib">
  <meta name="go-import" content="gonum.org/v1/hdf5 git https://github.com/gonum/hdf5">

  
  <meta name="go-source" content="gonum.org/v1/gonum https://github.com/gonum/gonum/ https://github.com/gonum/gonum/tree/master{/dir} https://github.com/gonum/gonum/blob/master{/dir}/{file}#L{line}"/>
  <meta name="go-source" content="gonum.org/v1/plot https://github.com/gonum/plot/ https://github.com/gonum/plot/tree/master{/dir} https://github.com/gonum/plot/blob/master{/dir}/{file}#L{line}"/>
  <meta name="go-source" content="gonum.org/v1/netlib https://github.com/gonum/netlib/ https://github.com/gonum/netlib/tree/master{/dir} https://github.com/gonum/netlib/blob/master{/dir}/{file}#L{line}"/>
  <meta name="go-source" content="gonum.org/v1/hdf5 https://github.com/gonum/hdf5/ https://github.com/gonum/hdf5/tree/master{/dir} https://github.com/gonum/hdf5/blob/master{/dir}/{file}#L{line}">

[...]
```

is there something else to be done? or... some caching effect somewhere?

**Comment by sbinet** [comment]
@btracey could you have a look at what happened?
what did I miss?

(because it seems that there still isn't any redirect in place for `gonum.org/v1/tools/...`)

**Comment by btracey** [comment]
Weird. The meta-tags are not on the source for the homepage. Why not?

**Comment by btracey** [comment]
Also, I think we need to add the `go-import` command to the 404 page as well.

**Comment by btracey** [comment]
Wait sorry, the problem is that this is not actually the website code any more. The website code is `gonum/website`. I believe this repo should be deleted.

**Comment by sbinet** [comment]
ah! :)

**Pull request merged**
