### PR TITLE
Newwebsite

### PR DESCRIPTION
**Pull request by btracey**

### CODE REVIEW

**Comment by btracey** [comment]
Series of commits updating to new website as discussed in https://github.com/gonum/gonum.github.io/pull/6#issuecomment-314141757

I'm not sure how to get the contributing document linked properly in the Join Us section within the contact widget, so I'm leaving that change for the future and will open an issue.

**Comment by kortschak** [comment]
Have a look at https://github.com/kortschak/kortschak.io for how I handle the theme and overriding parts I don't want from it.

**Comment by vladimir-ch** [comment]
* "GONUM"  in upper-case looks unusual but seems to be controlled by the theme
* The circular crop of the Gonum gopher doesn't look nice but again, seems to be controlled by the theme.
* When I run
```
cd _hugogonum
hugo -d ..
```
I get differences in relative paths like:
```
-      <a class="navbar-brand" href="/../">Gonum</a>
+      <a class="navbar-brand" href="/">Gonum</a>
```
or
```
-    <li><a href="../post/introtogonum/">The Gonum Numerical Computing Packages</a></li>
+    <li><a href="https://gonum.org/post/introtogonum/">The Gonum Numerical Computing Packages</a></li>
```

**Comment by kortschak** [comment]
There is control of the uppercasing in the config file. I altered mine without altering the theme file.

**Comment by kortschak** [comment]
*ping*

**Comment by btracey** [comment]
Sorry. I haven't spent the time to figure out how to do the modifications we want without modifying the hugo theme.

I was also talking with @spf13 , and he recommended we use netlify to host rather than github. Netlify apparently can read the github repository and run hugo. This would mean we can just modify the hugo files rather than also dealing with the generation and copy step. If that sounds good, I can figure out how to make it happen. It may be easier to get working with github first and then switch to netlify.

**Comment by btracey** [comment]
Namely, the modifications are having the meta-tags work and the thumbnail be the gonum logo instead of the academic license.

**Comment by kortschak** [comment]
SGTM

**Comment by btracey** [comment]
Is it better to have the theme untouched? We could keep it as is if we want to make some of the modications @vladimir-ch is suggesting.

**Comment by btracey** [comment]
(as is meaning part of the repo but in a place where we can modify it to our own theme over time)

**Comment by btracey** [comment]
Because if the latter I think this is ready as is, and I can try and figure out Netlify.

**Comment by kortschak** [comment]
Leaving the theme alone is how I deal with it.

See https://github.com/gcushen/hugo-academic/blob/4859cbe36a35e03ed060c8377982d802371009e9/static/css/hugo-academic.css#L901-L906 versus https://github.com/kortschak/kortschak.io/blob/master/static/css/hugo-academic.css#L899-L903. The `static/` directory can be used to provide replacement files (whether I'm doing this the right way is open to interpretation - it works though).

**Comment by btracey** [comment]
I wonder if it's better to change things now, in that if we wanted a more customized look it's probably easier down the road to modify the theme than to try and shoehorn around?

**Comment by btracey** [comment]
I understand your comment about the static directory though, and so we can at least get the meta tags to work that way by having the custom `404.html` and `index.html`. One of the things that's nice about modifying the theme is in the theme it's a preamble, so the change only has to be made once and it's copied everywhere.

**Comment by btracey** [comment]
@kortschak do you have a direction in which you want me to proceed?

**Comment by kortschak** [comment]
I would rather not make changes to the theme unless they cannot be done without that. Changing the theme brings the maintenance burden on to us.

The conflicts here have come from merging #4. It may be easier to close the PR and start from the current master.

See https://github.com/gcushen/hugo-academic/issues/211.

**Comment by btracey** [comment]
Okay, I got netlify running on my (shell of a) personal website. As mentioned above, it runs hugo and pushes to the public website so we don't need to manage that content.

My proposal is that I'll create a new repository "website". I'll do this PR in that repository. Assuming I've done it satisfactorily, then I'll switch the current DNS resolution from github to netlify, and we can delete this repository. Sound good?

**Comment by kortschak** [comment]
SGTM

**Comment by btracey** [comment]
Above plan has been implemented. Closing this and deleting the repository.

**Comment by btracey** [comment]
Actually, I'll wait a few hours to delete in case there are any objections.

**Pull request closed without merging**
